Importing required Libraries

In [28]:
import os
import sys

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import torch
import torchvision
from PIL import Image
from torchvision import transforms

Just to ensure the version of tools and library

In [29]:
print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

Platform: linux
Python version: 3.11.12 (main, Apr  9 2025, 08:55:54) [GCC 11.4.0]
---
matplotlib version: 3.10.0
pandas version: 2.2.2
PIL version: 11.2.1
torch version: 2.6.0+cu124
torchvision version: 0.21.0+cu124


# **Working with Tensors in PyTorch**

The term tensor comes from mathematics. It refers to an array of values organized into one or more dimensions.

In Python, there are several libraries for creating and manipulating tensors. In this program, we'll use PyTorch, which is built for deep learning. We'll build our computer visions with PyTorch.

In this section, we'll get familiar with tensors and what we can do with them. We'll begin making a 2-dimensional tensor from a nested list.

***Task 1.1.1: Use the nested list my_values to create the tensor my_tensor.***


In [30]:
# my_values = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
# my_tensor = ...

# print("my_tensor class:", type(my_tensor))
# print(my_tensor)


my_values = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_tensor = torch.tensor(my_values)

print("my_tensor class:", type(my_tensor))
print(my_tensor)

my_tensor class: <class 'torch.Tensor'>
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


# **Tensor Attributes**
Note that a PyTorch tensor is a class: Tensor(). Like any class, it has attributes that can provide us with information. For instance, the .shape attribute tells us the dimensions of the tensor, and the .dtype attribute tells us the data type of the values stored inside the tensor.

***Task 1.1.2: Print the dimensions and data type of my_tensor.***

In [31]:
# print("my_tensor shape:",...)

# print("my_tensor dtype:", ...)

print("my_tensor shape:",my_tensor.shape)

print("my_tensor dtype:", my_tensor.dtype)

my_tensor shape: torch.Size([4, 3])
my_tensor dtype: torch.int64


Tensors also have a .device attribute, which specifies the hardware on which it's stored. By default, tensors are created on the computer's CPU. Let's check if that's the case for my_tensor.

***Task 1.1.3: Print the device of my_tensor.***

In [32]:
print("my_tensor device:",my_tensor.device)

my_tensor device: cpu


Some computers come with GPUs, which allow for bigger and faster model building. In PyTorch, the cuda package is used to access GPUs on Linux and Windows machines; mps is used on Macs. Let's check what's available on the WQU virtual machines.



In [33]:
# Check if GPUs available via `cuda`
cuda_gpus_available = torch.cuda.is_available()

# Check if GPUs available via `mps`
mps_gpus_available = torch.backends.mps.is_available()

print("cuda GPUs available:", cuda_gpus_available)
print("mps GPUs available:", mps_gpus_available)

cuda GPUs available: True
mps GPUs available: False


***Task 1.1.4: Change the device of my_tensor to "cuda".***

In [34]:
# my_tensor = ...

# print("my_tensor device:", my_tensor.device)

my_tensor = my_tensor.to("cuda")

print("my_tensor device:", my_tensor.device)

my_tensor device: cuda:0


### Tensor Slicing

---


There are several ways to manipulate tensors. One important technique is slicing, where we use square brackets [] and indexing to select a subset of the values in a tensor.


---


***Task 1.1.5: Slice my_tensor, assigning its top two rows to left_tensor and its bottom two rows to right_tensor.***

In [35]:
# left_tensor = ...
# right_tensor = ...

left_tensor = my_tensor[:2 , :]
right_tensor = my_tensor[-2:, :]


print("left_tensor class:", type(left_tensor))
print("left_tensor shape:", left_tensor.shape)
print("left_tensor data type:", left_tensor.dtype)
print("left_tensor device:", left_tensor.device)
print(left_tensor)
print()
print("right_tensor class:", type(right_tensor))
print("right_tensor shape:", right_tensor.shape)
print("right_tensor data type:", right_tensor.dtype)
print("right_tensor device:", right_tensor.device)
print(right_tensor)

left_tensor class: <class 'torch.Tensor'>
left_tensor shape: torch.Size([2, 3])
left_tensor data type: torch.int64
left_tensor device: cuda:0
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

right_tensor class: <class 'torch.Tensor'>
right_tensor shape: torch.Size([2, 3])
right_tensor data type: torch.int64
right_tensor device: cuda:0
tensor([[ 7,  8,  9],
        [10, 11, 12]], device='cuda:0')


**General Syntax for Slicing a 2D Tensor**

new_tensor = original_tensor[start_row:end_row, start_col:end_col]

| What you want               | Syntax             |
| --------------------------- | ------------------ |
| All rows, all columns       | `tensor[:, :]`     |
| First 2 rows                | `tensor[:2, :]`    |
| Last 2 rows                 | `tensor[-2:, :]`   |
| First 3 columns             | `tensor[:, :3]`    |
| Row 1 to 3, Column 0 to 1   | `tensor[1:4, 0:2]` |
| Single row (e.g., row 2)    | `tensor[2, :]`     |
| Single column (e.g., col 1) | `tensor[:, 1]`     |


### Tensor Math

---


Another way to manipulate tensors is to use mathematical operations. For example, we can perform addition using either the + operator or the add() method.


---


***Task 1.1.6: Use both the mathematical operator and the class method to add left_tensor to right_tensor. Assign the results to summed_tensor_operator and summed_tensor_method, respectively.***

In [36]:
# summed_tensor_operator = ...
# summed_tensor_method = ...

summed_tensor_operator = left_tensor + right_tensor
summed_tensor_method = left_tensor.add(right_tensor)


print(summed_tensor_operator)
print()
print(summed_tensor_method)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')




---


One of the most important mathematical operations in deep learning is
multiplication, so let's spend some time on it here.

Keep in mind that, when it comes to tensors, there's more than one type of multiplication. For starters, there's **element-wise multiplication**, where the corresponding values of two tensors are multiplied together. In PyTorch, we can do this using the * operator or the .mul() method.


---

***Task 1.1.7: Use both the mathematical operator and the class method to multiply left_tensor to right_tensor. Assign the results to ew_tensor_operator and ew_tensor_method, respectively.***

In [37]:
# ew_tensor_operator = ...
# ew_tensor_method = ...

ew_tensor_operator = left_tensor * right_tensor
ew_tensor_method = left_tensor.mul(right_tensor)


print(ew_tensor_operator)
print()
print(ew_tensor_method)

tensor([[ 7, 16, 27],
        [40, 55, 72]], device='cuda:0')

tensor([[ 7, 16, 27],
        [40, 55, 72]], device='cuda:0')


Note that element-wise multiplication is **commutative**. It doesn't matter in what order we multiply the two tensors. The product of `left_tensor * right_tensor` is the same as the product of `right_tensor * left_tensor`.



In [38]:
left_tensor * right_tensor == right_tensor * left_tensor

tensor([[True, True, True],
        [True, True, True]], device='cuda:0')



---


Next, there's **matrix multiplication**, which combines the rows and columns of two tensors to generate a new one. We can use the `@` operator or the `.matmul()` method.

To see how this works, let's create two new tensors with different shapes.

In [39]:
new_left_tensor = torch.Tensor([[2, 5], [7, 3]])
new_right_tensor = torch.Tensor([[8], [9]])

print(new_left_tensor)
print()
print(new_right_tensor)

tensor([[2., 5.],
        [7., 3.]])

tensor([[8.],
        [9.]])



**Task 1.1.8:** Use both the mathematical operator and the class method to perform matrix multiplication on `new_left_tensor` and `new_right_tensor`. Assign the results to `mm_tensor_operator` and `mm_tensor_method`, respectively.

In [40]:
# mm_tensor_operator = ...
# mm_tensor_method = ...

mm_tensor_operator = new_left_tensor @ new_right_tensor
mm_tensor_method = new_left_tensor.matmul(new_right_tensor)


print(mm_tensor_operator)
print()
print(mm_tensor_method)

tensor([[61.],
        [83.]])

tensor([[61.],
        [83.]])


One very important thing to remember: matrix multiplication is **not commutative**. The number of columns in the tensor on the left must equal the number of rows in the tensor on the right. If these two dimensions don't match, your code will throw a `RunTimeError`.

In [41]:
mm_tensor_operator = new_right_tensor @ new_left_tensor

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x2)

<div class="alert alert-info" role="alert">
Matrix multiplication is the way your models will train and make predictions, and dimension mismatches will be a common source of bugs when you start building models. For that reason, it's always important to check the shape of your tensors. 🤓
</div>

---
Lastly, tensors come with methods for aggregation calculations. For instance, if we wanted to know the mean of all the elements in `my_tensor`, we'd use the `.mean()` method

---
***Task 1.1.9: Calculate the mean for all values in my_tensor.***

In [45]:
# my_tensor_mean = ...
my_tensor_mean = my_tensor.float().mean()

print("my_tensor mean:", my_tensor_mean)

my_tensor mean: tensor(6.5000, device='cuda:0')


Using `.mean()` by itself is helpful if we want to aggregate all the elements in a tensor, but more often we want to aggregate along one of the tensor's axes.

For example, what's the mean of each column in `my_tensor`? Remember that the dimensions of this tensor: `[4, 3]`. The first number in this list refers to the 4 rows, and the second to 3 columns. If we want the mean of each column, we need to reduce across the rows or first dimension. To do this, we use the `dim=` argument. And since Python uses 0-based indexing, we specify the first dimension with a `0`.
---
***Task 1.1.10: Calculate the mean for each column in my_tensor.***

In [46]:
# my_tensor_column_means = ...

my_tensor_column_means = my_tensor.float().mean(dim=0)

print("my_tensor column means:", my_tensor_column_means)

my_tensor column means: tensor([5.5000, 6.5000, 7.5000], device='cuda:0')


We now have some helpful tools for working with PyTorch tensors. We can check a tensor's shape, data type and device. We can manipulate a tensor by slicing it. We can perform mathematical operations on tensors, including matrix multiplication and aggregation calculations.

Up next, let's apply our new skills by exploring the dataset for this project.

### Explore Files

**Task 1.1.11:** Following the pattern of `data_dir`, assign the path to the multi-class training data to `train_dir`. ***bold text***